Finalterm/Models/Comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalterm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public int P_Id { get; set; }
        public string Comment1 { get; set; }
        public string C_Id { get; set; }
        public int Annonyms { get; set; }
        public string time { get; set; }
        public int rating { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}

Finalterm/Models/Message.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalterm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string Sender_Id { get; set; }
        public string Messages { get; set; }
        public int Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}

Finalterm/Controllers/MessageController.cs
using Finalterm.Interface;
using Finalterm.Models;
using Finalterm.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finalterm.Controllers
{
    public class MessageController : SecureController

    {
        IRepository<Message> repo = new MessageRepository(new FinalProjectEntities());
        // GET: Message
        [HttpGet]
        public ActionResult Index()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Index(Message mgs)
        {

            Message m = new Message();
            m.Sender_Id = mgs.Sender_Id;
            m.Messages = mgs.Messages;
            m.Status = 0;
            

            repo.Insert(m);
            return RedirectToAction("Index");

            //return RedirectToAction("Index","Message","<script>alert('Message Sent.Check Your Registered Email address or wait for reply.thank you');</script>");
        }
    }
}

Finalterm/Controllers/RupamOrderController.cs
using Finalterm.Interface;
using Finalterm.Models;
using Finalterm.Repository;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Finalterm.Controllers
{
    public class RupamOrderController : SecureController
    {
        IRepository<Order> Orrepo = new OrderRepository(new FinalProjectEntities());
        IRepository<Customer> crrepo = new CustomerRepository(new FinalProjectEntities());
        IRepository<Admin> adrepo = new AdminRepository(new FinalProjectEntities());
        IRepository<Login> lrepo = new LoginRepository(new FinalProjectEntities());
        IRepository<Catagory> crepo = new CatagoryRepository(new FinalProjectEntities());
        IRepository<Discount> drepo = new DiscountRepository(new FinalProjectEntities());
        IRepository<frentite> frepo = new FrontRepository(new FinalProjectEntities());
        IRepository<Product> prepo = new ProductRepostory(new FinalProjectEntities());
        IRepository<Comment> comrepo = new CommentRepository(new FinalProjectEntities());
        IRepository<Message> mrepo = new MessageRepository(new FinalProjectEntities());

          
        [HttpGet]
        public ActionResult NoOfOrder()
        {
            return View(Orrepo.GetAll().ToList());
        }
        [HttpPost]
        public ActionResult NoOfOrder(string name,string Select)
        {
            Session["done"] = 0;
            string temp;
            if (name.Equals(""))
            {
                return RedirectToAction("NoOfOrder");
            }
            List<Order> lo= Orrepo.GetAll().ToList();
            List<Order> lso = new List<Order>();
            Order o = new Order();
            foreach (var item in lo)
            {
                if(Select.Equals("Id"))
                {
                    if (name.Equals(item.ID.ToString()))
                    {
                        o.ID = item.ID;
                        o.Pay_id = item.Pay_id;
                        o.P_ID = item.P_ID;
                        o.Quantity = item.Quantity;
                        o.Sales = item.Sales;
                        o.Status = item.Status;
                        o.time = item.time;
                        o.C_Id = item.C_Id;
                        o.Customer = item.Customer;
                        o.Payment = item.Payment;
                        o.Product = item.Product;
                        Session["done"] = 1;
                        return View("OneOrder", o);
                    }
                }
                else if(Select.Equals("Name"))
                {
                    if (name.Equals(item.Customer.Name))
                    {
                        o.ID = item.ID;
                        o.Pay_id = item.Pay_id;
                        o.P_ID = item.P_ID;
                        o.Quantity = item.Quantity;
                        o.Sales = item.Sales;
                        o.Status = item.Status;
                        o.time = item.time;
                        o.C_Id = item.C_Id;
                        o.Customer = item.Customer;
                        o.Payment = item.Payment;
                        o.Product = item.Product;
                        Session["done"] = 1;
                        lso.Add(item);
                    }
                }
                else if (Select.Equals("Status"))
                {
                    if(name.ToUpper().Equals("PENDING"))
                    {
                        temp = "0";
                    }
                    else
                    {
                        temp = "1";
                    }
                    if (temp.Equals(item.Status.ToString()))
                    {
                        o.ID = item.ID;
                        o.Pay_id = item.Pay_id;
                        o.P_ID = item.P_ID;
                        o.Quantity = item.Quantity;
                        o.Sales = item.Sales;
                        o.Status = item.Status;
                        o.time = item.time;
                        o.C_Id = item.C_Id;
                        o.Customer = item.Customer;
                        o.Payment = item.Payment;
                        o.Product = item.Product;
                        lso.Add(item);
                        Session["done"] = 1;
                    }
                }
                else if (Select.Equals("Amount"))
                {
                    if (name.Equals(item.Payment.Amount.ToString()))
                    {
                        o.ID = item.ID;
                        o.Pay_id = item.Pay_id;
                        o.P_ID = item.P_ID;
                        o.Quantity = item.Quantity;
                        o.Sales = item.Sales;
                        o.Status = item.Status;
                        o.time = item.time;
                        o.C_Id = item.C_Id;
                        o.Customer = item.Customer;
                        o.Payment = item.Payment;
                        o.Product = item.Product;
                        Session["done"] = 1;
                        lso.Add(item);
                    }
                }

            }
            return View(lso);
            
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(Orrepo.GetById(id.ToString()));
        }
        [HttpPost]
        public ActionResult Details(Order o)
        {
            OrderRepository or = new OrderRepository(new FinalProjectEntities());
            o.time = DateTime.Now.ToString();
            or.update(o);
            return RedirectToAction("NoOfOrder");
        }
        public ActionResult Print(int id)
        {
            return View(Orrepo.GetById(id.ToString()));
        }
        public ActionResult CusDetails()
        {
            return View(crrepo.GetAll().ToList());
        }
        [HttpGet]
        public ActionResult cdetails(string id)
        {
            return View(crrepo.GetById(id));
        }
        [HttpPost]
        public ActionResult cdetails(Customer c, int Status)
        {
            //FinalProjectEntities f = new FinalProjectEntities();
            CustomerRepository cr = new CustomerRepository(new FinalProjectEntities());
            cr.update(c, Status);
            //Customer c1 = f.Customers.Find(c.Id);
            //Login l1 = f.Logins.Find(c.Id);
            //c1.Id = c.Id;
            //c1.Name = c.Name;
            //c1.PhoneNumber = c.PhoneNumber;
            //c1.Email = c.Email;
            //c1.Address = c.Address;
            //l1.Status = Status;
            //c1.Points = c1.Points;
            //try
            //{
            //    // Your code...
            //    // Could also be before try if you know the exception occurs in SaveChanges

            //    f.SaveChanges();
            //    return RedirectToAction("Memory");
            //}
            //catch (DbEntityValidationException e)
            //{
            //    foreach (var eve in e.EntityValidationErrors)
            //    {
            //        //return Content("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:" +
            //        //    eve.Entry.Entity.GetType().Name + " " + eve.Entry.State);
            //        foreach (var ve in eve.ValidationErrors)
            //        {
            //            return Content("- Property: \"{0}\", Error: \"{1}\"" +
            //                ve.PropertyName + "," + ve.ErrorMessage);
            //        }
            //    }
                return RedirectToAction("CusDetails");
            
        }
        public ActionResult Delete(string id)
        {
            Customer c = crrepo.GetById(id);
            crrepo.Delete(c);
            return RedirectToAction("CusDetails");
        }
        [HttpGet]
        public ActionResult AddEmployee()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddEmployee(Admin a)
        {
            if(ModelState.IsValid)
            {
                Login l = new Login();
                l.ID = a.Id;
                Random r = new Random();
                string s = r.Next(999).ToString();
                l.Password = s;
                l.Status = 0;
                l.Type = 1;
                l.Online = 0;
                lrepo.Insert(l);

                adrepo.Insert(a);

                try
                {
                    SmtpClient clientDetais = new SmtpClient();
                    clientDetais.Port = 587;
                    clientDetais.Host = "smtp.gmail.com";
                    clientDetais.EnableSsl = true;
                    clientDetais.DeliveryMethod = SmtpDeliveryMethod.Network;
                    clientDetais.UseDefaultCredentials = false;
                    clientDetais.Credentials = new NetworkCredential("librarymanagementSystemAIUB@gmail.com", "khalidhasan.khr");

                    MailMessage maildetails = new MailMessage();
                    maildetails.From = new MailAddress("librarymanagementSystemAIUB@gmail.com");
                    maildetails.To.Add(a.Email);
                    maildetails.Subject = "Account Created";
                    maildetails.Body = "Welcome to BuyHere " + a.Name + "\n Your Employee Id:" + a.Id + "AND YOUR PASSWORD IS " + s;
                    clientDetais.Send(maildetails);
                    return RedirectToAction("Admin", "Home");
                }
                catch (Exception)
                {
                    return RedirectToAction("Admin", "Home");
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult AddCatagory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCatagory(Catagory c)
        {
            if(ModelState.IsValid)
            {

Finalterm/Views/RupamOrder/AddProduct.cshtml
@model Finalterm.Models.Product


<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/CSS/bootstrap4.css">
    <link rel="stylesheet" href="~/CSS/custom.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Buy Here</title>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load('current', {
            packages: ['corechart']
        });
    </script>
</head>

<body>
    <div class="container-fluid bg-dark text-light" style="width:100;align-content:center" align="center">
        <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" style="align-content:center" width="200" height="200" />
    </div>
    @{
        if (Session["Login"].ToString().Equals("0"))
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        @*<div class="col-md-5"><i class="fa fa-envelope-o" aria-hidden="true"></i> debjyoti.das7@gmail.com</div>*@
                        <div class="col-md-3">

                        </div>

                        <div align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Login","Home")">Login</a></div>
                        @*<div class="col-md-2"> <i class="fa fa-cart-plus" aria-hidden="true"></i> My Cart - $ 0.00</div>*@
                        @*<div class="col-md-2"  align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Admin","Home")">Admin</a></div>*@
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        <div class="col-md-2" align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Logout","Home")">Logout</a></div>
                        <div class="col-md-3">
                            @*<div class="col-md-2" align="right"> <a href="@Url.Action("Index","Message")">Message to Admin</a></div>*@

                        </div>

                    </div>
                </div>
            </div>




        }
    }


    <div class="container-fluid bg-black">
        <nav class="container navbar navbar-expand-lg navbar-dark bg-black">
            <input name="Rupam" class="navbar-toggler" type="submit" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            @*<a href="@Url.Action("Admin","Home")" class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">Home</a>*@
            <span class="navbar-toggler-icon"></span>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="Admin">Home <span class="sr-only">(current)</span></a>
                    </li>
                    @*<li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="Index">Add employee</a>
                                <a class="dropdown-item" href="Index">Add Admin</a>
                                <a class="dropdown-item" href="Discount">Discount</a>
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="Index">Disabled</a>
                        </li>*@
                </ul>
                @*<form class="form-inline my-2 my-lg-0">
                        <input type="submit" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <input type="submit" class="btn btn-outline-success my-2 my-sm-0" type="input">Search</input>
                    </form>*@
            </div>
        </nav>
    </div>
    @using (Html.BeginForm("AddProduct", "RupamOrder", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Product</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Unit_Id, "Unit_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.DropDownList("Unit_Id", null, htmlAttributes: new { @class = "form-control" })*@
                    <input type="text" name="Unit_Id" value="" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Unit_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Catagory_Id, "Catagory_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.DropDownList("Catagory_Id", null, htmlAttributes: new { @class = "form-control" })*@
                    <input type="text" name="Catagory_Id" value="" class="form-control" />
                    @Html.ValidationMessageFor(model => model.Catagory_Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Buy_Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Buy_Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Buy_Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Sell_Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sell_Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sell_Price, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @* @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="image" class="form-control" />
                    @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
        <footer>
            <div class="container-fluid pt-5 pb-5 bg-dark text-light">
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="row">
                            </div>
                            <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" width="200" height="200" />

                        </div>
                        <div class="col-md-3 pl-4">
                            <div class="row">
                                <h5>About</h5>
                            </div>
                            <div class="row mb-4">
                                <div class="underline bg-light" style="width: 50px;"></div>
                            </div>
                            <div class="row">
                                <p>BuyHere.com.bd is the best online shopping site in bangladesh selling millions of products electronics products. Experience fast, reliable and trusted online shopping in bangladesh with home delivery anywhere across country. Find latest trends in fashion according to seasons and occasions with BuyHere online shopping and remain in style 24x7 and 365 days a year. BuyHere provides a facility of online shopping with cash on delivery to your home.</p>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="row">
                                <h5>Social Media</h5>
                            </div>
                            <div class="row mb-4">
                                <div class="underline bg-light" style="width: 50px;"></div>
                            </div>
                            <a href="https://www.facebook.com"><img src="https://img.icons8.com/color/48/000000/facebook.png"></a>
                            <a href="https://twitter.com"><img src="https://img.icons8.com/color/48/000000/twitter.png"></a>
                            @*<button class="btn btn-outline-light">Autunm</button> <button class="btn btn-outline-light">Dress</button> <button class="btn btn-outline-light">Fashion</button> <button class="btn btn-outline-light">Ladice Dress</button> <button class="btn btn-outline-light">Black Dress</button>*@
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

</body>
</html>