Finalterm/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finalterm.Models
{
    using Finalterm.Validation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Comments = new HashSet<Comment>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required,Range(5,200)]
        public int Quantity { get; set; }
        [Required,CheckUnitId]
        public int Unit_Id { get; set; }
        [Required,Catagorycheck]
        public int Catagory_Id { get; set; }
        [Required,Range(500,500000)]
        public double Buy_Price { get; set; }
        [Required, Range(500, 500000)]
        public double Sell_Price { get; set; }
        public int Rating { get; set; }
        public string image { get; set; }
        public string Brand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Catagory Catagory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Unit Unit { get; set; }
    }
}

Finalterm/Controllers/ProductsController.cs
using Finalterm.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using Finalterm.Models;

namespace Finalterm.Controllers
{
    public class ProductsController : Controller
    {
        ProductRepostory repo = new ProductRepostory(new Models.FinalProjectEntities());
        //GET: ProSearch
        public ActionResult Search(string searchVal, string brandsVal,string sort, int? page)
        {
           Session["search"] = searchVal;
            if(sort !=null && searchVal!=null)
            {
                return View(repo.GetBySort(sort,searchVal).ToPagedList(page ?? 1, 5));
            }
            if (brandsVal!=null)
            {
                return View(repo.GetByBrand(brandsVal).ToPagedList(page ?? 1, 5));
            }
           else
            {
                return View(repo.GetByString(searchVal).ToPagedList(page ?? 1, 5));
            }
            
        }
        public ActionResult Details(string id)
        {
            return View(repo.GetById(id));
        }
        public ActionResult Search1(string searchVal, string brandsVal, string sort, int? categoryVal, int? page)
        {
            Session["search"] = searchVal;
            if (sort != null && searchVal != null)
            {
                return View(repo.GetBySort(sort, searchVal).ToPagedList(page ?? 1, 5));
            }
            if (brandsVal != null)
            {
                return View(repo.GetByBrand(brandsVal).ToPagedList(page ?? 1, 5));
            }
            if (categoryVal != null)
            {
                return View(repo.GetByCategory(categoryVal).ToPagedList(page ?? 1, 5));
            }
            else
            {
                return View(repo.GetByString(searchVal).ToPagedList(page ?? 1, 5));
            }

        }
    }
}

Finalterm/Views/Products/Details.cshtml
@model Finalterm.Models.Product

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div class="container-fluid bg-dark text-light" style="width:100;align-content:center" align="center">
        <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" style="align-content:center" width="200" height="200" />
    </div>
    @{
        if (Session["Login"].ToString().Equals("0"))
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        @*<div class="col-md-5"><i class="fa fa-envelope-o" aria-hidden="true"></i> debjyoti.das7@gmail.com</div>*@
                        <div class="col-md-3">

                        </div>

                        <div align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Login","Home")">Login</a></div>
                        @*<div class="col-md-2"> <i class="fa fa-cart-plus" aria-hidden="true"></i> My Cart - $ 0.00</div>*@
                        @*<div class="col-md-2"  align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Admin","Home")">Admin</a></div>*@
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        <div class="col-md-2" align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Logout","Home")">Logout</a></div>
                        <div class="col-md-3">
                            <div class="col-md-2" align="right"> <a href="@Url.Action("Index","Message")">Message to Admin</a></div>

                        </div>

                    </div>
                </div>
            </div>




        }
    }
    <div>
        <h4>Product</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Quantity)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Quantity)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Buy_Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Buy_Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sell_Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sell_Price)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Rating)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Rating)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.image)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.image)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Catagory.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Catagory.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Unit.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Unit.Name)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    <footer>
        <div class="container-fluid pt-5 pb-5 bg-dark text-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                        </div>
                        <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" width="200" height="200" />

                    </div>
                    <div class="col-md-3 pl-4">
                        <div class="row">
                            <h5>About</h5>
                        </div>
                        <div class="row mb-4">
                            <div class="underline bg-light" style="width: 50px;"></div>
                        </div>
                        <div class="row">
                            <p>BuyHere.com.bd is the best online shopping site in bangladesh selling millions of products electronics products. Experience fast, reliable and trusted online shopping in bangladesh with home delivery anywhere across country. Find latest trends in fashion according to seasons and occasions with BuyHere online shopping and remain in style 24x7 and 365 days a year. BuyHere provides a facility of online shopping with cash on delivery to your home.</p>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="row">
                            <h5>Social Media</h5>
                        </div>
                        <div class="row mb-4">
                            <div class="underline bg-light" style="width: 50px;"></div>
                        </div>
                        <a href="https://www.facebook.com"><img src="https://img.icons8.com/color/48/000000/facebook.png"></a>
                        <a href="https://twitter.com"><img src="https://img.icons8.com/color/48/000000/twitter.png"></a>
                        @*<button class="btn btn-outline-light">Autunm</button> <button class="btn btn-outline-light">Dress</button> <button class="btn btn-outline-light">Fashion</button> <button class="btn btn-outline-light">Ladice Dress</button> <button class="btn btn-outline-light">Black Dress</button>*@
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

Finalterm/Views/Products/Search.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Finalterm.Models.Product>

@{
    Layout = null;
    Session["userId"] = "C001";
    List<string> brands = new List<string>();

    foreach (var item in Model)
    {
        if(brands.Contains(item.Brand))
        {

        }
        else
        {
            brands.Add(item.Brand);
        }
    }
}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/CSS/bootstrap4.css">
    <link rel="stylesheet" href="~/CSS/custom.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/CSS/SearchProducts.css">
    <title>project 4</title>
</head>

<body>
    <div class="container-fluid bg-dark text-light" style="width:100;align-content:center" align="center">
        <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" style="align-content:center" width="200" height="200" />
    </div>
    @{
        if (Session["Login"].ToString().Equals("0"))
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        @*<div class="col-md-5"><i class="fa fa-envelope-o" aria-hidden="true"></i> debjyoti.das7@gmail.com</div>*@
                        <div class="col-md-3">

                        </div>

                        <div align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Login","Home")">Login</a></div>
                        @*<div class="col-md-2"> <i class="fa fa-cart-plus" aria-hidden="true"></i> My Cart - $ 0.00</div>*@
                        @*<div class="col-md-2"  align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Admin","Home")">Admin</a></div>*@
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        <div class="col-md-2" align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Logout","Home")">Logout</a></div>
                        <div class="col-md-3">
                            <div class="col-md-2" align="right"> <a href="@Url.Action("Index","Message")">Message to Admin</a></div>

                        </div>

                    </div>
                </div>
            </div>




        }
    }


    <div class="container-fluid bg-black">
        <nav class="container navbar navbar-expand-lg navbar-dark bg-black">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                @using (Html.BeginForm("Search", "Products", FormMethod.Get))
                {
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="searchVal">
                    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search" />
                }

            </div>
        </nav>
    </div>
    <div class="mainbody">
        <div class="sidebar left">

            <div style="margin-left:20px; margin-top:20px;">
                <h4>Sort</h4>
            </div>
            <div style="margin-left:20px; font-size:15px;">
                <form action="" method="get">
                    <input type="hidden" name="searchVal" value=@Session["search"] />
                    <select class="form-control placeholder" name="sort" onchange="this.form.submit()">
                        <option value="">Select</option>
                        <option value="low">Price low to high</option>
                        <option value="high">Price high to low</option>
                    </select>
                </form>
            </div>

            <div style="margin-left:20px; margin-top:20px;">
                <h4>Brands</h4>
            </div>
            <div style="margin-left:40px; font-size:15px;">
                <form action="Search/" method="get">
                    @foreach (var item in brands)
                    {
                        <div>
                            <a href="Search?brandsVal=@item">@item</a>
                        </div>
                    }
                </form>
            </div>

        </div>
        <div>
            <table class="table">

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <div class="product">
                                <div>
                                    <a href="~/Home/Details/@item.Id">
                                        <img src="@Url.Content(item.image)" width="200" height="200" alt="Details" />
                                    </a>
                                </div>
                                <div>
                                    <h3><a href="Details/@item.Id">@item.Name</a></h3>
                                    <h5>@item.Sell_Price</h5>
                                    <h6>@item.Rating</h6>
                                    <form action="~/Carts/AddToCart" method="post">
                                        <input type="submit" name="AddToCart" value="AddToCart" class="btn btn-danger" />
                                        <input type="hidden" name="quantity" value="1" />
                                        <input type="hidden" name="productID" value=@item.Id />
                                    </form>
                                </div>
                            </div>

                        </td>

                    </tr>
                }

            </table>
            @Html.PagedListPager(Model, page => Url.Action("Search", new { page, searchVal = Request.QueryString["searchVal"] }))
        </div>
        <div class="sidebar right">

        </div>
    </div>
    <footer>
        <div class="container-fluid pt-5 pb-5 bg-dark text-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                        </div>
                        <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" width="200" height="200" />

                    </div>
                    <div class="col-md-3 pl-4">
                        <div class="row">
                            <h5>About</h5>
                        </div>
                        <div class="row mb-4">
                            <div class="underline bg-light" style="width: 50px;"></div>
                        </div>
                        <div class="row">
                            <p>BuyHere.com.bd is the best online shopping site in bangladesh selling millions of products electronics products. Experience fast, reliable and trusted online shopping in bangladesh with home delivery anywhere across country. Find latest trends in fashion according to seasons and occasions with BuyHere online shopping and remain in style 24x7 and 365 days a year. BuyHere provides a facility of online shopping with cash on delivery to your home.</p>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="row">
                            <h5>Social Media</h5>
                        </div>
                        <div class="row mb-4">
                            <div class="underline bg-light" style="width: 50px;"></div>
                        </div>
                        <a href="https://www.facebook.com"><img src="https://img.icons8.com/color/48/000000/facebook.png"></a>
                        <a href="https://twitter.com"><img src="https://img.icons8.com/color/48/000000/twitter.png"></a>
                        @*<button class="btn btn-outline-light">Autunm</button> <button class="btn btn-outline-light">Dress</button> <button class="btn btn-outline-light">Fashion</button> <button class="btn btn-outline-light">Ladice Dress</button> <button class="btn btn-outline-light">Black Dress</button>*@
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

Finalterm/Views/Products/Search1.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Finalterm.Models.Product>

@{
    Layout = null;
    Session["userId"] = "C001";
    List<string> brands = new List<string>();

    foreach (var item in Model)
    {
        if (brands.Contains(item.Brand))
        {

        }
        else
        {
            brands.Add(item.Brand);
        }
    }
}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="~/CSS/bootstrap4.css">
    <link rel="stylesheet" href="~/CSS/custom.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/CSS/SearchProducts.css">
    <title>project 4</title>
</head>

<body>
    <div class="container-fluid bg-dark text-light" style="width:100;align-content:center" align="center">
        <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" style="align-content:center" width="200" height="200" />
    </div>
    @{
        if (Session["Login"].ToString().Equals("0"))
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        @*<div class="col-md-5"><i class="fa fa-envelope-o" aria-hidden="true"></i> debjyoti.das7@gmail.com</div>*@
                        <div class="col-md-3">

                        </div>

                        <div align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Login","Home")">Login</a></div>
                        @*<div class="col-md-2"> <i class="fa fa-cart-plus" aria-hidden="true"></i> My Cart - $ 0.00</div>*@
                        @*<div class="col-md-2"  align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Admin","Home")">Admin</a></div>*@
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="container-fluid bg-dark header-top d-none d-md-block">
                <div class="container">
                    <div class="row text-light pt-2 pb-2">
                        <div class="col-md-2" align="right"> <i class="fa fa-user-o" aria-hidden="true"></i> <a href="@Url.Action("Logout","Home")">Logout</a></div>
                        <div class="col-md-3">
                            <div class="col-md-2" align="right"> <a href="@Url.Action("Index","Message")">Message to Admin</a></div>

                        </div>

                    </div>
                </div>
            </div>




        }
    }


    <div class="container-fluid bg-black">
        <nav class="container navbar navbar-expand-lg navbar-dark bg-black">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                @using (Html.BeginForm("Search", "Products", FormMethod.Get))
                {
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="searchVal">
                    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search" />
                }

            </div>
        </nav>
    </div>
    <div class="mainbody">
        <div class="sidebar left">

            <div style="margin-left:20px; margin-top:20px;">
                <h4>Sort</h4>
            </div>
            <div style="margin-left:20px; font-size:15px;">
                <form action="" method="get">
                    <input type="hidden" name="searchVal" value=@Session["search"] />
                    <select class="form-control placeholder" name="sort" onchange="this.form.submit()">
                        <option value="">Select</option>
                        <option value="low">Price low to high</option>
                        <option value="high">Price high to low</option>
                    </select>
                </form>
            </div>

            <div style="margin-left:20px; margin-top:20px;">
                <h4>Brands</h4>
            </div>
            <div style="margin-left:40px; font-size:15px;">
                <form action="Search/" method="get">
                    @foreach (var item in brands)
                    {
                        <div>
                            <a href="Search?brandsVal=@item">@item</a>
                        </div>
                    }
                </form>
            </div>

        </div>
        <div>
            <table class="table">

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <div class="product">
                                <div>
                                    <a href="~/Home/Details/@item.Id">
                                        <img src="@Url.Content(item.image)" width="200" height="200" alt="Details" />
                                    </a>
                                </div>
                                <div>
                                    <h3><a href="Details/@item.Id">@item.Name</a></h3>
                                    <h5>@item.Sell_Price</h5>
                                    <h6>@item.Rating</h6>
                                    <form action="~/Carts/AddToCart" method="post">
                                        <input type="submit" name="AddToCart" value="AddToCart" class="btn btn-danger" />
                                        <input type="hidden" name="quantity" value="1" />
                                        <input type="hidden" name="productID" value=@item.Id />
                                    </form>
                                </div>
                            </div>

                        </td>

                    </tr>
                }

            </table>
            @Html.PagedListPager(Model, page => Url.Action("Search", new { page, searchVal = Request.QueryString["searchVal"] }))
        </div>
        <div class="sidebar right">

        </div>
    </div>
    <footer>
        <div class="container-fluid pt-5 pb-5 bg-dark text-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="row">
                        </div>
                        <img src="~/Image/73474977_484313005624525_7008271267014901760_n.png" alt="Alternate Text" width="200" height="200" />

                    </div>
                    <div class="col-md-3 pl-4">
                        <div class="row">
                            <h5>About</h5>
                        </div>
                        <div class="row mb-4">
                            <div class="underline bg-light" style="width: 50px;"></div>
                        </div>
                        <div class="row">
                            <p>BuyHere.com.bd is the best online shopping site in bangladesh selling millions of products electronics products. Experience fast, reliable and trusted online shopping in bangladesh with home delivery anywhere across country. Find latest trends in fashion according to seasons and occasions with BuyHere online shopping and remain in style 24x7 and 365 days a year. BuyHere provides a facility of online shopping with cash on delivery to your home.</p>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="row">
                            <h5>Social Media</h5>
                        </div>
                        <div class="row mb-4">
                            <div class="underline bg-light" style="width: 50px;"></div>
                        </div>
                        <a href="https://www.facebook.com"><img src="https://img.icons8.com/color/48/000000/facebook.png"></a>
                        <a href="https://twitter.com"><img src="https://img.icons8.com/color/48/000000/twitter.png"></a>
                        @*<button class="btn btn-outline-light">Autunm</button> <button class="btn btn-outline-light">Dress</button> <button class="btn btn-outline-light">Fashion</button> <button class="btn btn-outline-light">Ladice Dress</button> <button class="btn btn-outline-light">Black Dress</button>*@
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>